---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secrets
  namespace: docfunc
spec:
  encryptedData:
  {{- range $key, $value := .Values.encryptedSecrets }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  template:
    metadata:
      creationTimestamp: null
      name: secrets
      namespace: docfunc
    type: Opaque
