docfuncVersion: 0.1.36

aws_bucket: blobs.docfunc.com
aws_url: https://blobs.docfunc.com

encryptedSecrets:
  algolia_app_id: null
  algolia_secret: null
  app_key: null
  aws_access_key_id: null
  aws_secret_access_key: null
  captcha_secret_key: null
  captcha_site_key: null
  mail_password: null
  mysql_password: null
  mysql_root_password: null
  redis_password: null
